#!/usr/bin/env bun
/**
 * Generates `reference-seeds.generated.ts` from `reference-seeds.source.xml`.
 *
 * The curated 60-seed corpus (E1.6a) is the editable source of truth. We emit
 * it as structured TypeScript rather than reading the .xml at runtime because:
 *   - bundling non-TS assets into dist/index.js is fragile (see the
 *     @huggingface/transformers bundling history) — a runtime fs read of an
 *     asset path inside the published bundle is exactly what we avoid;
 *   - embedding 116KB of arbitrary prose/code as a TS template literal risks
 *     backtick / ${} escaping bugs. JSON.stringify is escape-safe.
 *
 * Regenerate after editing the source corpus:
 *   bun run packages/plugin/scripts/build-reference-seeds.ts
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const SRC = resolve(here, "../src/hooks/magic-context/reference-seeds.source.xml");
const OUT = resolve(here, "../src/hooks/magic-context/reference-seeds.generated.ts");

const raw = readFileSync(SRC, "utf-8");

// Each seed unit begins with a single-line marker comment:
//   <!-- seed #N | imp=X | episode,types | model (run) -->
// followed by its <compartment> block and optional <facts>/<events>/<user_observations>.
const MARKER = /^<!-- seed #\d+ \|[^\n]*-->[ \t]*$/gm;
const markers = [...raw.matchAll(MARKER)];

if (markers.length === 0) {
  throw new Error("build-reference-seeds: no seed markers found in source corpus");
}

interface RawSeed {
  importance: number;
  block: string;
}

const seeds: RawSeed[] = [];
for (let i = 0; i < markers.length; i++) {
  const start = markers[i].index! + markers[i][0].length;
  const end = i + 1 < markers.length ? markers[i + 1].index! : raw.length;
  const block = raw.slice(start, end).trim();
  if (!block.startsWith("<compartment")) {
    throw new Error(
      `build-reference-seeds: seed #${i + 1} does not start with <compartment (got: ${block.slice(0, 40)}...)`,
    );
  }
  const impMatch = block.match(/<compartment[^>]*\bimportance="(\d+)"/);
  if (!impMatch) {
    throw new Error(`build-reference-seeds: seed #${i + 1} has no importance attribute`);
  }
  seeds.push({ importance: Number.parseInt(impMatch[1], 10), block });
}

const header = `// AUTO-GENERATED by scripts/build-reference-seeds.ts from reference-seeds.source.xml
// DO NOT EDIT BY HAND. Regenerate: bun run packages/plugin/scripts/build-reference-seeds.ts
//
// The 60-seed cross-project calibration corpus (E1.6a). Each \`block\` is a full
// example unit (compartment + optional facts/events/user_observations) that the
// historian reads as a calibration anchor for importance scoring, tier decay,
// and fact-extraction shape. NEVER treated as dedup-able project memory.

export interface ReferenceSeed {
  /** importance score parsed from the seed's <compartment importance="N"> attribute */
  readonly importance: number;
  /** full example XML unit (compartment + optional facts/events/user_observations) */
  readonly block: string;
}

export const REFERENCE_SEEDS: ReadonlyArray<ReferenceSeed> = ${JSON.stringify(seeds, null, 2)};
`;

writeFileSync(OUT, header, "utf-8");
console.log(
  `build-reference-seeds: emitted ${seeds.length} seeds (importance ${Math.min(
    ...seeds.map((s) => s.importance),
  )}..${Math.max(...seeds.map((s) => s.importance))}) → ${OUT}`,
);
