export {
    buildCompartmentBlock,
    escapeXmlAttr,
    escapeXmlContent,
    getCompartments,
    getSessionFacts,
    replaceAllCompartmentState,
    replaceAllCompartmentStateAndBumpDepth,
    type SessionFact,
} from "./compartment-storage";
export {
    clearCompressionDepth,
    getAverageCompressionDepth,
    getMaxCompressionDepth,
    incrementCompressionDepth,
} from "./compression-depth-storage";
export {
    clearIndexedMessages,
    deleteIndexedMessage,
} from "./message-index";
export { runMigrations } from "./migrations";
export {
    computeProjectDocsHash,
    readProjectDocsCanonical,
} from "./project-docs-hash";
export {
    normalizeStoredProjectPath,
    ProjectIdentityError,
    type ProjectIdentityErrorClass,
    resolveProjectIdentity,
    resolveProjectIdentityStrict,
} from "./project-identity";
export {
    applySqliteTuningPragmas,
    type ContextDatabase,
    closeDatabase,
    enforceSchemaFence,
    getDatabasePersistenceError,
    getPersistedSchemaVersion,
    initializeDatabase,
    isDatabasePersisted,
    LATEST_SUPPORTED_VERSION,
    type OpenDatabaseOptions,
    openDatabase,
    runSqliteOptimize,
    schemaVersionIsSupported,
    setSqlitePragmaConfig,
} from "./storage-db";
export {
    deleteIdentityRekeyMap,
    getIdentityRekeyMap,
    type IdentityRekeyMapRow,
    listIdentityRekeyMaps,
    upsertIdentityRekeyMap,
} from "./storage-identity-rekey-map";
export {
    clearM0MutationsForSession,
    deleteM0Mutation,
    getM0Mutation,
    getM0MutationsAfterId,
    getM0MutationsBySession,
    getMaxM0MutationId,
    type M0MutationLogRow,
    type M0MutationType,
    queueM0Mutation,
    queueM0Mutation as appendM0Mutation,
} from "./storage-m0-mutation-log";
export {
    getMaxMemoryMutationId,
    getMemoryMutation,
    getMemoryMutationsForRender,
    type MemoryMutationLogRow,
    type MemoryMutationType,
    queueMemoryMutation,
} from "./storage-memory-mutation-log";
export {
    type AppendAutoSearchHintOutcome,
    type AutoSearchHintDecision,
    appendAutoSearchHintDecision,
    appendNoteNudgeAnchor,
    clearCachedM0,
    clearCachedM0M1,
    clearDeferredExecutePendingIfMatches,
    clearDetectedContextLimit,
    clearEmergencyRecovery,
    clearHistorianFailureState,
    clearPendingCompactionMarkerStateIf,
    clearPendingPiCompactionMarkerStateIf,
    clearPersistedNoteNudge,
    clearPersistedNudgePlacement,
    clearPersistedReasoningWatermark,
    clearPersistedStickyTurnReminder,
    clearPersistedTodoSyntheticAnchor,
    clearSession,
    type DeferredExecutePayload,
    deliverNoteNudgeAtomic,
    getAutoSearchHintDecisions,
    getHistorianFailureState,
    getNoteLastReadAt,
    getNoteNudgeAnchors,
    getOrCreateSessionMeta,
    getOverflowState,
    getPendingCompactionMarkerState,
    getPendingPiCompactionMarkerState,
    getPersistedNoteNudge,
    getPersistedNudgePlacement,
    getPersistedReasoningWatermark,
    getPersistedStickyTurnReminder,
    getPersistedTodoSyntheticAnchor,
    getSessionsWithPendingMarker,
    getSessionsWithPendingPiMarker,
    getSessionWorkMetrics,
    getStrippedPlaceholderIds,
    incrementHistorianFailure,
    loadPersistedUsage,
    type PendingCompactionMarker,
    type PendingPiCompactionMarker,
    type PersistCachedM0Payload,
    type PersistedOverflowState,
    type PersistedTodoSyntheticAnchor,
    peekDeferredExecutePending,
    persistCachedM0,
    pruneAutoSearchHintDecisions,
    pruneNoteNudgeAnchors,
    recordDetectedContextLimit,
    recordOverflowDetected,
    removeAutoSearchHintDecisionByMessageId,
    removeNoteNudgeAnchorByMessageId,
    removeStrippedPlaceholderId,
    setDeferredExecutePendingIfAbsent,
    setNoteLastReadAt,
    setPendingCompactionMarkerState,
    setPendingPiCompactionMarkerState,
    setPersistedNudgePlacement,
    setPersistedReasoningWatermark,
    setPersistedStickyTurnReminder,
    setPersistedTodoSyntheticAnchor,
    setSessionWorkMetrics,
    setStrippedPlaceholderIds,
    updateSessionMeta,
} from "./storage-meta";
export { bumpSessionFactsVersion } from "./storage-meta-shared";
export {
    addNote,
    deleteNote,
    dismissNote,
    getNotes,
    getPendingSmartNotes,
    getReadySmartNotes,
    getSessionNotes,
    getSmartNotes,
    markNoteChecked,
    markNoteReady,
    type Note,
    type NoteStatus,
    type NoteType,
    replaceAllSessionNotes,
    updateNote,
} from "./storage-notes";
export {
    clearPendingOps,
    getPendingOps,
    queuePendingOp,
    removePendingOp,
} from "./storage-ops";
export {
    bumpProjectMemoryEpoch,
    bumpProjectUserProfileVersion,
    deleteProjectState,
    ensureProjectState,
    GLOBAL_USER_PROFILE_PROJECT_PATH,
    getProjectState,
    type ProjectStateRow,
    setProjectState,
} from "./storage-project-state";
export {
    getSourceContents,
    replaceSourceContent,
    saveSourceContent,
} from "./storage-source";
export {
    getSubagentInvocations,
    getSubagentTotalsBySubagent,
    recordSubagentInvocation,
    type SubagentInvocationInput,
    type SubagentInvocationRow,
    type SubagentKind,
    type SubagentTotals,
} from "./storage-subagent-invocations";
export {
    adoptFallbackTagMessageId,
    deleteTagsByMessageId,
    findAdoptableFallbackTags,
    getActiveTagsBySession,
    getMaxDroppedTagNumber,
    getMaxTagNumberBySession,
    getTagById,
    getTagsByNumbers,
    getTagsBySession,
    getTopNBySize,
    insertTag,
    updateCavemanDepth,
    updateTagDropMode,
    updateTagMessageId,
    updateTagStatus,
} from "./storage-tags";
export {
    clearV22BackfillFailures,
    deleteV22BackfillFailure,
    getV22BackfillFailure,
    listV22BackfillFailures,
    recordV22BackfillFailure,
    type V22BackfillErrorClass,
    type V22BackfillFailureRow,
} from "./storage-v22-backfill-failures";
