export {
    type AppendAutoSearchHintOutcome,
    type AutoSearchHintDecision,
    appendAutoSearchHintDecision,
    appendNoteNudgeAnchor,
    clearDeferredExecutePendingIfMatches,
    clearDetectedContextLimit,
    clearEmergencyRecovery,
    clearHistorianFailureState,
    clearPendingCompactionMarkerStateIf,
    clearPendingPiCompactionMarkerStateIf,
    clearPersistedNoteNudge,
    clearPersistedNudgePlacement,
    clearPersistedReasoningWatermark,
    clearPersistedStickyTurnReminder,
    clearPersistedTodoSyntheticAnchor,
    type DeferredExecutePayload,
    deliverNoteNudgeAtomic,
    getAutoSearchHintDecisions,
    getHistorianFailureState,
    getNoteLastReadAt,
    getNoteNudgeAnchors,
    getOverflowState,
    getPendingCompactionMarkerState,
    getPendingPiCompactionMarkerState,
    getPersistedNoteNudge,
    getPersistedNudgePlacement,
    getPersistedReasoningWatermark,
    getPersistedStickyTurnReminder,
    getPersistedTodoSyntheticAnchor,
    getSessionsWithPendingMarker,
    getSessionsWithPendingPiMarker,
    getStrippedPlaceholderIds,
    incrementHistorianFailure,
    loadPersistedUsage,
    type PendingCompactionMarker,
    type PendingPiCompactionMarker,
    type PersistedOverflowState,
    type PersistedTodoSyntheticAnchor,
    peekDeferredExecutePending,
    pruneAutoSearchHintDecisions,
    pruneNoteNudgeAnchors,
    recordDetectedContextLimit,
    recordOverflowDetected,
    removeAutoSearchHintDecisionByMessageId,
    removeNoteNudgeAnchorByMessageId,
    removeStrippedPlaceholderId,
    setDeferredExecutePendingIfAbsent,
    setNoteLastReadAt,
    setPendingCompactionMarkerState,
    setPendingPiCompactionMarkerState,
    setPersistedNudgePlacement,
    setPersistedReasoningWatermark,
    setPersistedStickyTurnReminder,
    setPersistedTodoSyntheticAnchor,
    setStrippedPlaceholderIds,
} from "./storage-meta-persisted";
export {
    clearSession,
    getOrCreateSessionMeta,
    updateSessionMeta,
} from "./storage-meta-session";
