export {
    buildCompartmentBlock,
    escapeXmlAttr,
    escapeXmlContent,
    getCompartments,
    getSessionFacts,
    replaceAllCompartmentState,
    type SessionFact,
} from "./compartment-storage";
export {
    clearCompressionDepth,
    getAverageCompressionDepth,
    getMaxCompressionDepth,
    incrementCompressionDepth,
} from "./compression-depth-storage";
export {
    clearIndexedMessages,
    deleteIndexedMessage,
} from "./message-index";
export {
    type ContextDatabase,
    closeDatabase,
    getDatabasePersistenceError,
    isDatabasePersisted,
    openDatabase,
} from "./storage-db";
export {
    type AppendAutoSearchHintOutcome,
    type AutoSearchHintDecision,
    appendAutoSearchHintDecision,
    appendNoteNudgeAnchor,
    clearDeferredExecutePendingIfMatches,
    clearDetectedContextLimit,
    clearEmergencyRecovery,
    clearHistorianFailureState,
    clearPendingCompactionMarkerStateIf,
    clearPendingPiCompactionMarkerStateIf,
    clearPersistedNoteNudge,
    clearPersistedNudgePlacement,
    clearPersistedReasoningWatermark,
    clearPersistedStickyTurnReminder,
    clearPersistedTodoSyntheticAnchor,
    clearSession,
    type DeferredExecutePayload,
    deliverNoteNudgeAtomic,
    getAutoSearchHintDecisions,
    getHistorianFailureState,
    getNoteLastReadAt,
    getNoteNudgeAnchors,
    getOrCreateSessionMeta,
    getOverflowState,
    getPendingCompactionMarkerState,
    getPendingPiCompactionMarkerState,
    getPersistedNoteNudge,
    getPersistedNudgePlacement,
    getPersistedReasoningWatermark,
    getPersistedStickyTurnReminder,
    getPersistedTodoSyntheticAnchor,
    getSessionsWithPendingMarker,
    getSessionsWithPendingPiMarker,
    getStrippedPlaceholderIds,
    incrementHistorianFailure,
    loadPersistedUsage,
    type PendingCompactionMarker,
    type PendingPiCompactionMarker,
    type PersistedOverflowState,
    type PersistedTodoSyntheticAnchor,
    peekDeferredExecutePending,
    pruneAutoSearchHintDecisions,
    pruneNoteNudgeAnchors,
    recordDetectedContextLimit,
    recordOverflowDetected,
    removeAutoSearchHintDecisionByMessageId,
    removeNoteNudgeAnchorByMessageId,
    removeStrippedPlaceholderId,
    setDeferredExecutePendingIfAbsent,
    setNoteLastReadAt,
    setPendingCompactionMarkerState,
    setPendingPiCompactionMarkerState,
    setPersistedNudgePlacement,
    setPersistedReasoningWatermark,
    setPersistedStickyTurnReminder,
    setPersistedTodoSyntheticAnchor,
    setStrippedPlaceholderIds,
    updateSessionMeta,
} from "./storage-meta";
export {
    addNote,
    deleteNote,
    dismissNote,
    getNotes,
    getPendingSmartNotes,
    getReadySmartNotes,
    getSessionNotes,
    getSmartNotes,
    markNoteChecked,
    markNoteReady,
    type Note,
    type NoteStatus,
    type NoteType,
    replaceAllSessionNotes,
    updateNote,
} from "./storage-notes";
export {
    clearPendingOps,
    getPendingOps,
    queuePendingOp,
    removePendingOp,
} from "./storage-ops";
export {
    getSourceContents,
    replaceSourceContent,
    saveSourceContent,
} from "./storage-source";
export {
    deleteTagsByMessageId,
    getActiveTagsBySession,
    getMaxDroppedTagNumber,
    getMaxTagNumberBySession,
    getTagById,
    getTagsByNumbers,
    getTagsBySession,
    getTopNBySize,
    insertTag,
    updateCavemanDepth,
    updateTagDropMode,
    updateTagMessageId,
    updateTagStatus,
} from "./storage-tags";
