export {
    type AppendAutoSearchHintOutcome,
    type AutoSearchHintDecision,
    addStaleReduceStrippedIds,
    appendAutoSearchHintDecision,
    appendNoteNudgeAnchor,
    applyStrippedPlaceholderDelta,
    type Channel2NudgeState,
    casChannel2NudgeState,
    clearDeferredExecutePendingIfMatches,
    clearDetectedContextLimit,
    clearEmergencyRecovery,
    clearHistorianFailureState,
    clearPendingCompactionMarkerStateIf,
    clearPendingPiCompactionMarkerStateIf,
    clearPersistedNoteNudge,
    clearPersistedReasoningWatermark,
    clearPersistedTodoSyntheticAnchor,
    type DeferredExecutePayload,
    DRAIN_WINDOW_MS,
    deliverNoteNudgeAtomic,
    getAutoSearchHintDecisions,
    getChannel2NudgeClaimedAt,
    getChannel2NudgeState,
    getHistorianFailureState,
    getLastNudgeLevel,
    getLastNudgeUndropped,
    getNoteLastReadAt,
    getNoteNudgeAnchors,
    getOverflowState,
    getPendingCompactionMarkerState,
    getPendingPiCompactionMarkerState,
    getPersistedNoteNudge,
    getPersistedReasoningWatermark,
    getPersistedTodoSyntheticAnchor,
    getSessionsWithPendingMarker,
    getSessionsWithPendingPiMarker,
    getSessionWorkMetrics,
    getStaleReduceStrippedIds,
    getStrippedPlaceholderIds,
    incrementHistorianFailure,
    loadPersistedUsage,
    loadProtectedTailMeta,
    markProtectedTailPolicyV3Seeded,
    type PendingCompactionMarker,
    type PendingPiCompactionMarker,
    type PersistedChannel1NudgeLevel,
    type PersistedOverflowState,
    type PersistedTodoSyntheticAnchor,
    type PersistedUsageState,
    type ProtectedTailDrainReservation,
    type ProtectedTailDrainReserveResult,
    type ProtectedTailMeta,
    type ProtectedTailSeedResult,
    peekDeferredExecutePending,
    protectedTailWindowBudget,
    pruneAutoSearchHintDecisions,
    pruneNoteNudgeAnchors,
    recordDetectedContextLimit,
    recordOverflowDetected,
    recordProtectedTailNoEligibleHead,
    recordProtectedTailPublicationFloor,
    removeAutoSearchHintDecisionByMessageId,
    removeNoteNudgeAnchorByMessageId,
    removeStrippedPlaceholderId,
    reserveProtectedTailDrainTokens,
    resetLastNudgeCycle,
    resetProtectedTailNoEligibleHead,
    rollbackProtectedTailDrainReservation,
    setChannel2NudgeState,
    setDeferredExecutePendingIfAbsent,
    setLastNudgeLevel,
    setLastNudgeUndropped,
    setNoteLastReadAt,
    setPendingCompactionMarkerState,
    setPendingPiCompactionMarkerState,
    setPersistedReasoningWatermark,
    setPersistedTodoSyntheticAnchor,
    setSessionWorkMetrics,
    setStrippedPlaceholderIds,
} from "./storage-meta-persisted";
export {
    clearSession,
    getOrCreateSessionMeta,
    updateSessionMeta,
} from "./storage-meta-session";
export {
    clearCachedM0,
    clearCachedM0M1,
    type PersistCachedM0Payload,
    persistCachedM0,
} from "./storage-meta-shared";
